// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lazjlpbikhpaxyhcrsbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhempscGJpa2hwYXh5aGNyc2JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTU5NDAsImV4cCI6MjA3MTY5MTk0MH0.eYs6uICuyvyB2DqXLZhO00OSmeO3tDl56GfBz0KPzBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});